alicpp_raw_data:
  folder_path_train: ../data/train
  folder_path_test: ../data/test

minIO_config:
  endpoint: localhost:9000
  access_key: minio_access_key
  secret_key: minio_secret_key
  bronze_bucket_name: bronze-alicpp
  bronze_folder_name_train: train
  bronze_folder_name_test: test
  folder_common: commonfeatures
  silver_bucket_name: silver-alicpp
  silver_folder_name_train: train
  silver_folder_name_test: test
  silver_folder_name_train_1M: train_1M # for fast testing
  silver_folder_name_test_1M: test_1M # for fast testing

Postgres_config:
  POSTGRES_DB: k6
  POSTGRES_USER: k6
  POSTGRES_PASSWORD: k6
  POSTGRES_HOST: 127.0.0.1 # replace your postgres host
  POSTGRES_PORT: 5432

